import type { ThemeDefinition } from '@qdb/shared';

export const LIGHT_THEME: ThemeDefinition = {
  id: 'default-light',
  themeCode: 'light',
  themeName: 'Default Light',
  primaryColor: '#0078d4',
  backgroundColor: '#ffffff',
  surfaceColor: '#f5f5f5',
  textPrimaryColor: '#242424',
  textSecondaryColor: '#616161',
  borderColor: '#d1d1d1',
  errorColor: '#d13438',
  successColor: '#107c10',
  warningColor: '#ca5010',
  fontFamily: 'Segoe UI, system-ui, sans-serif',
  baseFontSize: '14px',
  borderRadius: '4px',
  shadowStyle: 'Subtle',
  spacingScale: 'Normal',
  isDarkMode: false,
  isActive: true,
};

export const DARK_THEME: ThemeDefinition = {
  id: 'default-dark',
  themeCode: 'dark',
  themeName: 'Default Dark',
  primaryColor: '#479ef5',
  backgroundColor: '#1b1a19',
  surfaceColor: '#292827',
  textPrimaryColor: '#ffffff',
  textSecondaryColor: '#c8c6c4',
  borderColor: '#484644',
  errorColor: '#f1707b',
  successColor: '#54b054',
  warningColor: '#fcba19',
  fontFamily: 'Segoe UI, system-ui, sans-serif',
  baseFontSize: '14px',
  borderRadius: '4px',
  shadowStyle: 'Subtle',
  spacingScale: 'Normal',
  isDarkMode: true,
  isActive: false,
};

export const CORPORATE_QDB_THEME: ThemeDefinition = {
  id: 'corporate-qdb',
  themeCode: 'corporate-qdb',
  themeName: 'QDB Corporate Banking',
  primaryColor: '#003366',
  secondaryColor: '#c8a951',
  backgroundColor: '#f8f9fa',
  surfaceColor: '#ffffff',
  textPrimaryColor: '#1a1a2e',
  textSecondaryColor: '#4a4a68',
  borderColor: '#c8d0d8',
  errorColor: '#c0392b',
  successColor: '#1e8449',
  warningColor: '#d35400',
  fontFamily: '"Inter", "Segoe UI", system-ui, sans-serif',
  fontUrl:
    'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
  baseFontSize: '14px',
  headingFontSize: '20px',
  labelFontSize: '13px',
  borderRadius: '2px',
  shadowStyle: 'Subtle',
  spacingScale: 'Comfortable',
  isDarkMode: false,
  isActive: false,
};
