// BRD FR-SCHEMA-004: qdb_portal_configs
// Primary name: qdb_portal_name (BRD-authoritative from PortalConfigService.ts selectFields())
// Column names are exactly what PortalConfigService queries — do not rename.
import type { EntityMetadataPayload } from '../../types/DataverseMetadata.js';
import { label, requiredLevel, booleanField, globalPicklist } from './shared.js';

export const portalConfigsDefinition: EntityMetadataPayload = {
  '@odata.type': 'Microsoft.Dynamics.CRM.EntityMetadata',
  SchemaName: 'qdb_Portal_Configs',
  DisplayName: label('Portal Configuration'),
  DisplayCollectionName: label('Portal Configurations'),
  Description: label('Branding, navigation, and auth configuration for the citizen portal.'),
  OwnershipType: 'OrganizationOwned',
  HasActivities: false,
  HasNotes: false,
  IsActivity: false,
  PrimaryNameAttribute: 'qdb_portal_name',
  Attributes: [
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_PortalName',
      LogicalName: 'qdb_portal_name',
      DisplayName: label('Portal Name'),
      RequiredLevel: requiredLevel('ApplicationRequired'),
      MaxLength: 255,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_LogoUrl',
      LogicalName: 'qdb_logo_url',
      DisplayName: label('Logo URL'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 500,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_FaviconUrl',
      LogicalName: 'qdb_favicon_url',
      DisplayName: label('Favicon URL'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 500,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_PrimaryColor',
      LogicalName: 'qdb_primary_color',
      DisplayName: label('Primary Color'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 20,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_AccentColor',
      LogicalName: 'qdb_accent_color',
      DisplayName: label('Accent Color'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 20,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_FontFamily',
      LogicalName: 'qdb_font_family',
      DisplayName: label('Font Family'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 100,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_BackgroundColor',
      LogicalName: 'qdb_background_color',
      DisplayName: label('Background Color'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 20,
    },
    {
      ...globalPicklist('qdb_NavLayout', 'qdb_nav_layout', 'Navigation Layout', 'qdb_nav_layout'),
      RequiredLevel: requiredLevel('ApplicationRequired'),
    },
    {
      ...globalPicklist('qdb_SidebarDefaultState', 'qdb_sidebar_default_state', 'Sidebar Default State', 'qdb_sidebar_default_state'),
      RequiredLevel: requiredLevel('ApplicationRequired'),
    },
    {
      ...globalPicklist('qdb_AuthProvider', 'qdb_auth_provider', 'Authentication Provider', 'qdb_auth_provider'),
      RequiredLevel: requiredLevel('ApplicationRequired'),
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_SsoProviders',
      LogicalName: 'qdb_sso_providers',
      DisplayName: label('SSO Providers (JSON)'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 1000,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_LandingPage',
      LogicalName: 'qdb_landing_page',
      DisplayName: label('Landing Page'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 255,
    },
    {
      ...booleanField('qdb_RtlEnabled', 'qdb_rtl_enabled', 'RTL Enabled', false),
      RequiredLevel: requiredLevel('ApplicationRequired'),
    },
    {
      ...booleanField('qdb_HeaderShowEntitySwitcher', 'qdb_header_show_entity_switcher', 'Show Entity Switcher', false),
      RequiredLevel: requiredLevel('ApplicationRequired'),
    },
    {
      ...booleanField('qdb_HeaderShowSupport', 'qdb_header_show_support', 'Show Support Link', false),
      RequiredLevel: requiredLevel('ApplicationRequired'),
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_HeaderSupportLabel',
      LogicalName: 'qdb_header_support_label',
      DisplayName: label('Support Label'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 255,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_HeaderSupportUrl',
      LogicalName: 'qdb_header_support_url',
      DisplayName: label('Support URL'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 500,
    },
    {
      ...booleanField('qdb_HeaderShowNotifications', 'qdb_header_show_notifications', 'Show Notifications', true),
      RequiredLevel: requiredLevel('ApplicationRequired'),
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_FooterLeftLogoUrl',
      LogicalName: 'qdb_footer_left_logo_url',
      DisplayName: label('Footer Left Logo URL'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 500,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_FooterRightLogoUrl',
      LogicalName: 'qdb_footer_right_logo_url',
      DisplayName: label('Footer Right Logo URL'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 500,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_FooterPoweredByText',
      LogicalName: 'qdb_footer_powered_by_text',
      DisplayName: label('Footer Powered By Text'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 255,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.MemoAttributeMetadata',
      SchemaName: 'qdb_FooterLinks',
      LogicalName: 'qdb_footer_links',
      DisplayName: label('Footer Links (JSON)'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 4000,
    },
    {
      // CHALLENGE 6 note: Column Security Profile must be applied post-creation.
      // See PROVISIONING-COMPLETE.md for manual step details.
      '@odata.type': 'Microsoft.Dynamics.CRM.MemoAttributeMetadata',
      SchemaName: 'qdb_AuthConfigJson',
      LogicalName: 'qdb_auth_config_json',
      DisplayName: label('Auth Config JSON'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 4000,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.IntegerAttributeMetadata',
      SchemaName: 'qdb_NotificationPollIntervalSeconds',
      LogicalName: 'qdb_notification_poll_interval_seconds',
      DisplayName: label('Notification Poll Interval (Seconds)'),
      RequiredLevel: requiredLevel('ApplicationRequired'),
      MinValue: 10,
      MaxValue: 120,
      DefaultValue: 30,
    },
  ],
};
