// BRD FR-SCHEMA-007: qdb_portal_services
// Primary name: qdb_title (BRD-authoritative from services.ts DataverseService interface)
import type { EntityMetadataPayload } from '../../types/DataverseMetadata.js';
import { label, requiredLevel, booleanField } from './shared.js';

export const portalServicesDefinition: EntityMetadataPayload = {
  '@odata.type': 'Microsoft.Dynamics.CRM.EntityMetadata',
  SchemaName: 'qdb_Portal_Services',
  DisplayName: label('Portal Service'),
  DisplayCollectionName: label('Portal Services'),
  Description: label('Service catalogue entries for the citizen portal.'),
  OwnershipType: 'OrganizationOwned',
  HasActivities: false,
  HasNotes: false,
  IsActivity: false,
  PrimaryNameAttribute: 'qdb_title',
  Attributes: [
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_Title',
      LogicalName: 'qdb_title',
      DisplayName: label('Service Title (EN)'),
      RequiredLevel: requiredLevel('ApplicationRequired'),
      MaxLength: 255,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_TitleAr',
      LogicalName: 'qdb_title_ar',
      DisplayName: label('Service Title (AR)'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 255,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_Code',
      LogicalName: 'qdb_code',
      DisplayName: label('Service Code'),
      RequiredLevel: requiredLevel('ApplicationRequired'),
      MaxLength: 100,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.MemoAttributeMetadata',
      SchemaName: 'qdb_ShortDescription',
      LogicalName: 'qdb_short_description',
      DisplayName: label('Short Description (EN)'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 4000,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.MemoAttributeMetadata',
      SchemaName: 'qdb_ShortDescriptionAr',
      LogicalName: 'qdb_short_description_ar',
      DisplayName: label('Short Description (AR)'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 4000,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.MemoAttributeMetadata',
      SchemaName: 'qdb_FullDescription',
      LogicalName: 'qdb_full_description',
      DisplayName: label('Full Description (EN)'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 4000,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.MemoAttributeMetadata',
      SchemaName: 'qdb_FullDescriptionAr',
      LogicalName: 'qdb_full_description_ar',
      DisplayName: label('Full Description (AR)'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 4000,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_CategoryTag',
      LogicalName: 'qdb_category_tag',
      DisplayName: label('Category Tag'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 100,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_ImageUrl',
      LogicalName: 'qdb_image_url',
      DisplayName: label('Image URL'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 500,
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.StringAttributeMetadata',
      SchemaName: 'qdb_FormCode',
      LogicalName: 'qdb_form_code',
      DisplayName: label('Form Code (DFE)'),
      RequiredLevel: requiredLevel('None'),
      MaxLength: 100,
    },
    {
      ...booleanField('qdb_IsActive', 'qdb_is_active', 'Is Active', true),
      RequiredLevel: requiredLevel('ApplicationRequired'),
    },
    {
      '@odata.type': 'Microsoft.Dynamics.CRM.IntegerAttributeMetadata',
      SchemaName: 'qdb_DisplayOrder',
      LogicalName: 'qdb_display_order',
      DisplayName: label('Display Order'),
      RequiredLevel: requiredLevel('ApplicationRequired'),
      DefaultValue: 0,
    },
  ],
};
