import {
  AlignLeftRegular,
  AppsRegular,
  ArrowUploadRegular,
  CodeRegular,
  CalendarRegular,
  ToggleLeftRegular,
  CheckboxCheckedRegular,
  ChevronCircleDownRegular,
  ClipboardCheckmarkRegular,
  ClipboardTextLtrRegular,
  ClockRegular,
  DataBarVerticalRegular,
  DocumentRegular,
  GridDotsRegular,
  InfoRegular,
  LayoutCellFourRegular,
  LayoutColumnThreeRegular,
  LineHorizontal1Regular,
  MailRegular,
  MoneyRegular,
  MultiselectLtrRegular,
  NumberSymbolRegular,
  PhoneRegular,
  PuzzlePieceRegular,
  RadioButtonRegular,
  RectangleLandscapeRegular,
  SearchRegular,
  AlignTopRegular,
  TableCellsMergeRegular,
  TableRegular,
  TabRegular,
  TextEditStyleRegular,
  TextFieldRegular,
  TextFontSizeRegular,
} from '@fluentui/react-icons';
import type { FluentIcon } from '@fluentui/react-icons';
import { FIELD_TYPE, type FieldType } from '@/constants/fieldTypes';

export const FIELD_TYPE_ICONS: Record<FieldType, FluentIcon> = {
  [FIELD_TYPE.TEXT]: TextFieldRegular,
  [FIELD_TYPE.LABEL]: TextFieldRegular,   // DFE-FBE-001 read-only display field
  [FIELD_TYPE.TEXTAREA]: AlignLeftRegular,
  [FIELD_TYPE.NUMBER]: NumberSymbolRegular,
  [FIELD_TYPE.DECIMAL]: NumberSymbolRegular,
  [FIELD_TYPE.CURRENCY]: MoneyRegular,
  [FIELD_TYPE.DATE]: CalendarRegular,
  [FIELD_TYPE.DATETIME]: ClockRegular,
  [FIELD_TYPE.EMAIL]: MailRegular,
  [FIELD_TYPE.PHONE]: PhoneRegular,
  [FIELD_TYPE.DROPDOWN]: ChevronCircleDownRegular,
  [FIELD_TYPE.MULTI_SELECT]: MultiselectLtrRegular,
  [FIELD_TYPE.LOOKUP]: SearchRegular,
  [FIELD_TYPE.CHECKBOX]: CheckboxCheckedRegular,
  [FIELD_TYPE.RADIO]: RadioButtonRegular,
  [FIELD_TYPE.FILE_UPLOAD]: ArrowUploadRegular,
  [FIELD_TYPE.RICH_TEXT]: TextEditStyleRegular,
  [FIELD_TYPE.TAB]: TabRegular,
  [FIELD_TYPE.SECTION_1COL]: RectangleLandscapeRegular,
  [FIELD_TYPE.SECTION_2COL]: LayoutCellFourRegular,
  [FIELD_TYPE.SECTION_3COL]: LayoutColumnThreeRegular,
  [FIELD_TYPE.SECTION_CARD]: TableCellsMergeRegular,
  [FIELD_TYPE.SECTION_ACCORDION]: ChevronCircleDownRegular,
  [FIELD_TYPE.SPACER]: AlignTopRegular,
  [FIELD_TYPE.DIVIDER]: LineHorizontal1Regular,
  [FIELD_TYPE.INFO_TEXT]: InfoRegular,
  [FIELD_TYPE.HEADER_TEXT]: TextFontSizeRegular,
  [FIELD_TYPE.REPEATING_GRID]: TableRegular,
  [FIELD_TYPE.CHILD_ENTITY_GRID]: GridDotsRegular,
  [FIELD_TYPE.DOCUMENT_UPLOAD]: DocumentRegular,
  [FIELD_TYPE.TERMS_BLOCK]: ClipboardTextLtrRegular,
  [FIELD_TYPE.DECLARATION_BLOCK]: ClipboardCheckmarkRegular,
  [FIELD_TYPE.SUMMARY_BLOCK]: DataBarVerticalRegular,
  [FIELD_TYPE.CUSTOM]: CodeRegular,
  // Sprint 4
  [FIELD_TYPE.BOOLEAN]: ToggleLeftRegular,
  [FIELD_TYPE.INFO_CARD]: InfoRegular,
  [FIELD_TYPE.INTERACTIVE_GRID]: TableRegular,
};

export { AppsRegular, LayoutCellFourRegular, PuzzlePieceRegular };
