// Bridges Dataverse metadata into the GoRules canvas: builds a JSON Schema for the
// rule's target entity and pins it on the Input node, so the JDM decision table and
// expression editors autocomplete REAL entity fields with real types (one N:1 hop
// included). The schema is annotated (x-edp-*) so the PCRM translator can emit
// typed, bound inputs instead of guessing Text.

import type { DecisionGraphType } from '@gorules/jdm-editor';
import { listAttributes, listRelationships, type AttributeMeta, type RelationshipMeta } from '../metadata/metadataService';
import { category, pcrmType } from '../table/tableModel';

/** Marks a schema as generated by the designer for a given entity — only marked schemas are ever overwritten. */
export const ENTITY_MARKER = 'x-edp-entity';

type JsonObject = Record<string, unknown>;

function propertyFor(attr: AttributeMeta): JsonObject {
  const cat = category(attr.type);
  const shape: JsonObject =
    cat === 'number' ? { type: 'number' }
      : cat === 'boolean' ? { type: 'boolean' }
        : cat === 'date' ? { type: 'string', format: 'date-time' }
          : cat === 'optionset' ? { type: 'number' }
            : { type: 'string' };
  return { ...shape, description: attr.displayName, 'x-edp-type': pcrmType(attr.type) };
}

const isScalar = (a: AttributeMeta) => a.type !== 'Lookup' && a.type !== 'Customer' && a.type !== 'Owner';

/** Pure schema assembly — testable without metadata I/O. */
export function schemaFromMetadata(
  entity: string,
  attrs: AttributeMeta[],
  rels: RelationshipMeta[],
  relAttrs: Record<string, AttributeMeta[]>
): JsonObject {
  const properties: JsonObject = {};
  for (const a of attrs.filter(isScalar)) properties[a.logicalName] = propertyFor(a);
  for (const r of rels) {
    const nested = (relAttrs[r.relationship] ?? []).filter(isScalar);
    if (!nested.length) continue;
    properties[r.relationship] = {
      type: 'object',
      description: `${r.displayName} (${r.targetEntity})`,
      [ENTITY_MARKER]: r.targetEntity,
      'x-edp-relationship': r.relationship,
      properties: Object.fromEntries(nested.map((a) => [a.logicalName, propertyFor(a)])),
    };
  }
  return { type: 'object', [ENTITY_MARKER]: entity, description: `Fields of ${entity}`, properties };
}

/** Entity schema from live metadata: anchor fields + one hop into each business N:1 parent. */
export async function buildEntitySchema(entity: string): Promise<JsonObject> {
  const [attrs, rels] = await Promise.all([listAttributes(entity), listRelationships(entity)]);
  const relAttrs: Record<string, AttributeMeta[]> = {};
  await Promise.all(rels.map(async (r) => {
    try { relAttrs[r.relationship] = await listAttributes(r.targetEntity); } catch { /* parent stays scalar-less */ }
  }));
  return schemaFromMetadata(entity, attrs, rels, relAttrs);
}

/**
 * Return a graph whose Input node carries the entity schema. A schema the author
 * wrote by hand (no x-edp-entity marker) is never overwritten. Adds an Input node
 * when the canvas has none yet.
 */
export function withEntitySchema(graph: DecisionGraphType, schema: JsonObject): DecisionGraphType {
  const json = JSON.stringify(schema, null, 2);
  const nodes: any[] = [...((graph as any).nodes ?? [])];
  const idx = nodes.findIndex((n) => n.type === 'inputNode');
  if (idx < 0) {
    nodes.unshift({ id: 'edp-input', type: 'inputNode', name: 'request', position: { x: 80, y: 140 }, content: { schema: json } });
    return { ...(graph as any), nodes, edges: (graph as any).edges ?? [] };
  }
  const node = nodes[idx];
  const existing: string = node.content?.schema ?? '';
  if (existing === json) return graph;
  if (existing && !existing.includes(ENTITY_MARKER)) return graph; // hand-written — leave it alone
  nodes[idx] = { ...node, content: { ...node.content, schema: json } };
  return { ...(graph as any), nodes };
}
