export const TRANSLATABLE_FIELDS: Record<string, string[]> = {
  qdb_form_definition: [
    'qdb_title',
    'qdb_description',
    'qdb_confirmation_message',
    'qdb_infocard_back_label',
    'qdb_infocard_continue_label',
    'qdb_infocard_start_label',
    'qdb_infocard_skip_label',
  ],
  qdb_form_tab: ['qdb_label'],
  qdb_form_section: ['qdb_label', 'qdb_description'],
  qdb_form_field: [
    'qdb_label',
    'qdb_placeholder',
    'qdb_tooltip',
    'qdb_prefix',
    'qdb_suffix',
    'qdb_true_label',
    'qdb_false_label',
    'qdb_info_card_title',
    'qdb_info_card_body',
    'qdb_info_card_download_label',
    'qdb_file_download_label',
  ],
  qdb_form_option_value: ['qdb_label', 'qdb_description', 'qdb_notes'],
  qdb_grid_column_config: ['qdb_column_label'],
  qdb_info_card_screen: ['qdb_heading', 'qdb_sub_heading', 'qdb_icon_alt_text'],
  qdb_info_card_section: ['qdb_section_title', 'qdb_note_text'],
  qdb_info_card_item: ['qdb_item_title', 'qdb_item_description'],
  qdb_form_validation_rule: ['qdb_error_message'],
  qdb_form_button: ['qdb_label', 'qdb_confirmation_message'],
};

export const ENTITY_LABEL: Record<string, string> = {
  qdb_form_definition: 'Form',
  qdb_form_tab: 'Tab',
  qdb_form_section: 'Section',
  qdb_form_field: 'Field',
  qdb_form_option_value: 'Option Value',
  qdb_grid_column_config: 'Grid Column',
  qdb_info_card_screen: 'Info Card Screen',
  qdb_info_card_section: 'Info Card Section',
  qdb_info_card_item: 'Info Card Item',
  qdb_form_validation_rule: 'Validation Rule',
  qdb_form_button: 'Button',
};

export const FIELD_LABEL: Record<string, string> = {
  qdb_title: 'Title',
  qdb_description: 'Description',
  qdb_confirmation_message: 'Confirmation Message',
  qdb_infocard_back_label: 'Back Button Label',
  qdb_infocard_continue_label: 'Continue Button Label',
  qdb_infocard_start_label: 'Start Button Label',
  qdb_infocard_skip_label: 'Skip Button Label',
  qdb_label: 'Label',
  qdb_placeholder: 'Placeholder',
  qdb_tooltip: 'Tooltip',
  qdb_prefix: 'Prefix',
  qdb_suffix: 'Suffix',
  qdb_true_label: 'True Label',
  qdb_false_label: 'False Label',
  qdb_info_card_title: 'Info Card Title',
  qdb_info_card_body: 'Info Card Body',
  qdb_info_card_download_label: 'Download Label',
  qdb_file_download_label: 'File Download Label',
  qdb_notes: 'Notes',
  qdb_column_label: 'Column Label',
  qdb_heading: 'Heading',
  qdb_sub_heading: 'Sub Heading',
  qdb_icon_alt_text: 'Icon Alt Text',
  qdb_section_title: 'Section Title',
  qdb_note_text: 'Note Text',
  qdb_item_title: 'Item Title',
  qdb_item_description: 'Item Description',
  qdb_error_message: 'Error Message',
  qdb_confirmation_message_btn: 'Confirmation Message',
};
