<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qdb.ReportEngine.Core\Qdb.ReportEngine.Core.csproj" />
    <ProjectReference Include="..\Qdb.ReportEngine.Execution\Qdb.ReportEngine.Execution.csproj" />
  </ItemGroup>

</Project>
